name: Edward Pike Photo
favicon: null
layout_spectrum: 0.49849
typography_spectrum: 0.49697
title: Edward Pike Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#20c0f3'
    - '#b8ad7c'
    - '#2b3140'
    - '#e8ebf2'
  brandStrength: 0.578988587949425
  lightness: 0.19684603461064398
  saturation: 0.15526702580973506
  rhythmicContrast: 0.35911617102101445
purpose: []
